const c=document.getElementById('game'),x=c.getContext('2d'),hint=document.getElementById('startHint');x.imageSmoothingEnabled=false;
const W=c.width,H=c.height,keys={},P={x:100,y:420,s:4},state={scene:'title',step:0,boss:0,alive:0,stops:0,mirrors:0,choice:0,muted:false};
const scenes=['village','infinite','casino','mirror','citadel','ending'];
const notify=['🔥 Someone you don\'t know posted something!','You have 1 completely unnecessary notification.','Your screen misses you.'];
let note='',noteT=0,last=0;
const dialogs={
 village:[['Ada','The Tech Lords discovered something more valuable than gold.'],['Robin','Diamonds?'],['Ada','Attention. Every minute Scrollshire gives away strengthens them.'],['Ada','Take this Attention Compass. It points toward where attention is being harvested.'],['Robin','So I steal attention back from the algorithms and return it to the people?'],['Ada','Exactly. Try not to sound too pleased with yourself.']],
 infinite:[['Lord Infinite','Welcome! You may leave whenever you want.'],['Robin','Then where\'s the exit?'],['Lord Infinite','Oh, somewhere below the next video.'],['Lord Infinite','I never FORCE anyone to stay.'],['CHOICE','A) You removed every reason to stop.\nB) People should simply have more self-control.\nC) Endless scrolling is not necessarily bad.'],['Ada','Self-control matters. But environments matter too. A chapter ending gives your brain a stopping cue. Infinite feeds remove that cue.'],['Lord Infinite','How rude. I call it frictionless delight.'],['Robin','I call it hiding the door. Activate the three STOP signs!']],
 casino:[['Lady Maybe','Some videos are boring.'],['Robin','You\'re admitting that?'],['Lady Maybe','Of course! That\'s the secret.'],['Lady Maybe','Boring. Boring. Funny. Boring. AMAZING. Every swipe asks: what if the NEXT one is good?'],['Robin','So disappointment actually helps you?'],['Lady Maybe','Disappointment is simply suspense wearing an ugly hat.'],['Lady Maybe','My machines are only invitations. You can inspect every one...'],['Robin','Or I can walk straight past them.'],['Lady Maybe','...I liked you better before that sentence.']],
 mirror:[['Sir Algorithm','I simply give people what they appear to want.'],['Robin','Appear to want?'],['Sir Algorithm','Pause, replay, like, share, skip—I remember all of it. Eventually every feed becomes different.'],['Robin','That can actually be useful.'],['Sir Algorithm','Precisely. Hobbies. Niche communities. Music. Learning. I am not inherently your enemy.'],['Sir Algorithm','But I do not need to know what makes you happy. I only need to learn what makes you stay.'],['CHOICE','A) Optimise for happiness instead.\nB) People should control the algorithm.\nC) Destroy all algorithms!'],['Sir Algorithm','Control is the interesting word. Redirect my Attention Data toward USER CHOICE.'],['Robin','Finally, a boss fight involving settings.']],
 citadel:[['King Engagement','I gave everyone infinite entertainment. Creators reach audiences. People discover music, humour and ideas. And the service is free.'],['Robin','And then measured success by how difficult it was to leave.'],['King Engagement','Nobody is physically forced to use it.'],['Robin','True. Individual choice matters. So does what the environment is designed to reward.'],['King Engagement','Why read twenty pages when I can give you twenty stories in twenty seconds?'],['Robin','Because some things only become interesting AFTER twenty seconds.'],['Robin','The biggest cost isn\'t only what people watch. It\'s what they don\'t do while watching. Homework. Sleep. Friends. Hobbies.'],['Robin','And the strangest moment is when “I opened the app because I chose to” becomes “I opened it before I realised I had.”'],['King Engagement','So what would you do instead?'],['CHOICE','1) DESTROY THE SCROLLSTONES\n2) DO NOTHING\n3) RETURN CONTROL TO THE PEOPLE']]
};
function tone(f=440,d=.06){if(state.muted)return;try{const a=tone.a||(tone.a=new AudioContext()),o=a.createOscillator(),g=a.createGain();o.type='square';o.frequency.value=f;g.gain.value=.025;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch{}}
function box(name,text){x.fillStyle='rgba(8,8,12,.9)';x.fillRect(45,360,870,145);x.strokeStyle='#e8dca8';x.lineWidth=3;x.strokeRect(45,360,870,145);x.fillStyle='#ffe991';x.font='bold 20px monospace';x.fillText(name,70,393);x.fillStyle='#fff';x.font='18px monospace';wrap(text,70,425,815,25)}
function wrap(t,a,b,m,l){for(const para of t.split('\n')){let line='';for(const w of para.split(' ')){if(x.measureText(line+w).width>m){x.fillText(line,a,b);b+=l;line=''}line+=w+' '}x.fillText(line,a,b);b+=l}}
function px(a,b,w,h,col){x.fillStyle=col;x.fillRect(a,b,w,h)}
function robin(){px(P.x-8,P.y-14,16,18,'#2e9b50');px(P.x-6,P.y-20,12,7,'#174d2c');px(P.x-4,P.y+4,4,8,'#5b3728');px(P.x+2,P.y+4,4,8,'#5b3728');px(P.x+7,P.y-8,12,2,'#b98d52')}
function villager(a,b,col='#a86'){px(a-7,b-12,14,18,col);px(a-5,b-18,10,7,'#d9a36c');px(a-5,b-6,10,7,'#71c9e8')}
function title(){x.fillStyle='#10121b';x.fillRect(0,0,W,H);for(let i=0;i<70;i++)px((i*137)%W,(i*83)%H,2,2,'#d8d29c');x.fillStyle='#80d76c';x.font='bold 48px monospace';x.textAlign='center';x.fillText('THE OUTLAW OF ATTENTION',W/2,190);x.fillStyle='#ffe991';x.font='28px monospace';x.fillText('STEAL BACK YOUR TIME',W/2,235);x.fillStyle='#fff';x.font='17px monospace';x.fillText('A short retro story adventure',W/2,300);x.textAlign='left'}
function village(){x.fillStyle=state.alive?'#72b85d':'#657a58';x.fillRect(0,0,W,H);for(let i=0;i<5;i++){px(80+i*185,80,130,95,'#81513d');px(70+i*185,70,150,20,'#483a42')}px(0,300,W,85,'#b99b69');for(let i=0;i<7;i++)villager(110+i*125,270,state.alive?'#c57':'#777');if(state.alive){px(300,220,5,35,'#6b3');px(290,210,25,12,'#f66');x.fillStyle='#fff';x.font='15px monospace';x.fillText('Scrollshire is waking up.',20,30)}else{x.fillStyle='#d7efff';x.font='14px monospace';x.fillText('Everyone is staring at a Scrollstone.',20,30)}robin();x.fillStyle='#ffe991';x.fillText('Ada →',830,330)}
function arena(kind){x.fillStyle=kind===1?'#342443':kind===2?'#4e202d':kind===3?'#25374c':'#201d2c';x.fillRect(0,0,W,H);if(kind===1){for(let i=0;i<8;i++)px(120+i*95,60,55,250,'#151821');for(let i=0;i<3;i++){let a=200+i*260,b=260;px(a,b,55,45,state.stops>i?'#52c96c':'#a74747');x.fillStyle='#fff';x.fillText('STOP',a+7,b+28)}}if(kind===2){for(let i=0;i<6;i++){let a=95+i*140;px(a,150,75,120,'#5a405d');px(a+10,165,55,45,['#899','#f77','#ffdc68'][i%3]);x.fillStyle='#fff';x.fillText('?',a+33,195)}}if(kind===3){for(let i=0;i<3;i++){let a=220+i*230;px(a,170,50,70,state.mirrors>i?'#6ed2d8':'#8492a6');x.strokeStyle='#cff';x.beginPath();x.moveTo(a+5,230);x.lineTo(a+45,180);x.stroke()}px(760,140,130,90,'#364');x.fillStyle='#fff';x.fillText('USER',795,175);x.fillText('CHOICE',780,205)}robin()}
function citadel(){x.fillStyle='#17131e';x.fillRect(0,0,W,H);px(360,70,240,190,'#422c43');px(445,95,70,110,'#79615b');for(let i=0;i<25;i++)px(60+(i%13)*70,280+Math.floor(i/13)*25,45,8,'#72d6ff');x.fillStyle='#ffe991';x.font='17px monospace';x.fillText('CITADEL OF ENGAGEMENT',350,40);robin()}
function draw(){x.textAlign='left';if(state.scene==='title')title();else if(state.scene==='village')village();else if(state.scene==='infinite')arena(1);else if(state.scene==='casino')arena(2);else if(state.scene==='mirror')arena(3);else if(state.scene==='citadel')citadel();else ending();if(dialogs[state.scene]&&state.step<dialogs[state.scene].length){const d=dialogs[state.scene][state.step];box(d[0],d[1])}if(noteT>0){x.fillStyle='#fff';x.fillRect(560,18,380,42);x.fillStyle='#111';x.font='14px monospace';x.fillText(note,575,44)}}
function ending(){x.fillStyle='#0d1117';x.fillRect(0,0,W,H);x.textAlign='center';if(state.choice===1){x.fillStyle='#ffb36b';x.font='28px monospace';x.fillText('THE EMPTY KINGDOM',W/2,115);x.fillStyle='#fff';x.font='17px monospace';wrap('The Scrollstones vanish. Then a cook misses recipe videos, an artist loses an audience, and a musician loses a discovery channel. Freedom from technology is not the same as freedom with technology.',190,170,590,26)}else if(state.choice===2){x.fillStyle='#9ac7ff';x.font='27px monospace';x.fillText('ENDLESS CREDITS',W/2,90);for(let i=0;i<13;i++)x.fillText(['ONE MORE CLIP','JUST FIVE MINUTES','YOU MAY ALSO LIKE','ARE YOU STILL WATCHING?'][i%4],W/2,145+i*28);x.fillStyle='#ffe991';x.fillText('PRESS ENTER TO STOP SCROLLING',W/2,515)}else{x.fillStyle='#7ee58c';x.font='28px monospace';x.fillText('CONTROL RETURNED',W/2,95);x.fillStyle='#fff';x.font='17px monospace';wrap('Finite feeds. Visible timers. Optional autoplay. Session limits. Intentional breaks. Chronological choices. Recommendation controls. People still use Scrollstones—but they also talk, play, read, make art, exercise and sleep.',185,145,600,25);x.fillStyle='#ffe991';x.font='22px monospace';x.fillText('YOUR ATTENTION IS YOUR TIME.',W/2,390);x.fillText('Use technology deliberately.',W/2,430)}x.textAlign='left'}
function advance(){if(state.scene==='title'){state.scene='village';state.step=0;hint.style.display='none';tone(520);return}if(state.scene==='ending'){if(state.choice===2){state.choice=3;tone(700)}return}const ds=dialogs[state.scene]||[];if(state.step<ds.length-1){state.step++;tone(440);return}if(state.scene==='village'){state.scene='infinite';state.step=0;P.x=100;P.y=420}else if(state.scene==='infinite'){if(state.stops<3)return;state.alive=1;state.scene='casino';state.step=0}else if(state.scene==='casino'){state.scene='mirror';state.step=0}else if(state.scene==='mirror'){if(state.mirrors<3)return;state.scene='citadel';state.step=0}else if(state.scene==='citadel'){return}}
function interact(){if(state.scene==='infinite'&&state.step===dialogs.infinite.length-1){for(let i=0;i<3;i++){let a=227+i*260;if(Math.abs(P.x-a)<75&&Math.abs(P.y-280)<90&&state.stops===i){state.stops++;tone(700)}}if(state.stops===3){state.step=dialogs.infinite.length-1;setTimeout(()=>{state.scene='casino';state.step=0;P.x=100;P.y=420;state.alive=1},500)}return}if(state.scene==='mirror'&&state.step===dialogs.mirror.length-1){for(let i=0;i<3;i++){let a=245+i*230;if(Math.abs(P.x-a)<80&&Math.abs(P.y-210)<100&&state.mirrors===i){state.mirrors++;tone(760)}}if(state.mirrors===3)setTimeout(()=>{state.scene='citadel';state.step=0;P.x=100;P.y=420},500);return}advance()}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if([' ','Enter','e','E'].includes(e.key)){e.preventDefault();if(state.scene==='citadel'&&state.step===dialogs.citadel.length-1){state.choice=3;state.scene='ending';tone(800)}else interact()}if(state.scene==='citadel'&&state.step===dialogs.citadel.length-1&&['1','2','3'].includes(e.key)){state.choice=+e.key;state.scene='ending';tone(800)}if(e.key.toLowerCase()==='m')state.muted=!state.muted});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
function update(t){const dt=Math.min(2,(t-last)/16.67||1);last=t;if(!['title','ending'].includes(state.scene)&&!(dialogs[state.scene]&&state.step<dialogs[state.scene].length-1)){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);P.x=Math.max(20,Math.min(W-20,P.x+dx*P.s*dt));P.y=Math.max(40,Math.min(340,P.y+dy*P.s*dt))}if(noteT>0)noteT-=dt;else if(state.scene!=='title'&&Math.random()<.0012){note=notify[Math.floor(Math.random()*notify.length)];noteT=150;tone(950,.04)}draw();requestAnimationFrame(update)}requestAnimationFrame(update);
